version: '3'
services:
  nginx:
    image: nginx:1.12
    ports:
      - '8000:80'
      - '8001:8001'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php-fpm
      - npm_manage
      - npm_app
  php-fpm:
    build: "./docker/php-fpm/"
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zzmyphp-fpm.conf
    links:
      - db
      - db-test
  db:
    image: postgres:9.6.15
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
      - LC_ALL=C
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/db:/var/lib/postgresql/data

